""" Constant used by winafl scripts """

WINAFL_PATH = ""
WINAFL_BIN = ""
AUTOIT_BIN = ""
WINAFL_WORKING_DIR = ""
DYNAMORIO_PATH = ""
DRRUN = ""
WINAFLDLL = ""
WINAFL_DEFAULT_TIMEOUT = 0
WINAFL_LAST_PATH_TIMEOUT = 0
WINAFL_FUZZING_ITERATION = 0
WINAFL_AUTOIT_STOP = ""

