""" Constant used by winafl scripts """

WINAFL_PATH = ""
WINAFL_BIN = "afl-fuzz.exe"
WINAFL_DLL = "winafl.dll"
AUTOIT_BIN = ""
WINAFL_WORKING_DIR = ""
DYNAMORIO_PATH = ""
DRRUN_BIN = "drrun.exe"
WINAFL_DEFAULT_TIMEOUT = 0
WINAFL_LAST_PATH_TIMEOUT = 0
WINAFL_FUZZING_ITERATION = 0
WINAFL_LOOP_ITERATION = 0
WINAFL_AUTOIT_STOP = ""

