path_pin:
  /home/taxicat/work/pin-3.2-81205-gcc-linux/
path_tool:
  /home/taxicat/work/pin-3.2-81205-gcc-linux/source/tools/taint/
path_sienna:
  /home/taxicat/work/sienna-locomotive/
path_tmp:
  /tmp/
path_program: 
  /home/taxicat/work/target/clamav-0.99.2/clamscan/.libs/
program_name:
  lt-clamscan
program_arch:
  64
program_params:
  - -d
  - /home/taxicat/Downloads/fd480db8-cd02-4503-8fc3-fc41f8092097-H.ldb
  - /home/taxicat/work/target/clamav-0.99.2/clamscan/clamscan
tainted_file:
  fd480db8-cd02-4503-8fc3-fc41f8092097-H.ldb
