path_pin:
  /home/taxicat/work/pin-3.2-81205-gcc-linux/
path_tool:
  /home/taxicat/work/pin-3.2-81205-gcc-linux/source/tools/taint/
path_sienna:
  /home/taxicat/work/sienna-locomotive/
path_tmp:
  /tmp/
path_program: 
  /home/taxicat/work/sienna-locomotive/triage/corpus/asm/
program_name:
  crashy_mccrashface
program_arch:
  64
program_params:
  - 13
tainted_file:
  /tmp/crash_scratch
