path_program: 
  C:\Program Files\SumatraPDF\SumatraPDF.exe
path_autoit:
  C:\Program Files\AutoIt3\AutoIt3.exe
path_autoit_script:
  C:\..paths..\sumatra.au3 
path_radamsa:
  C:\cygwin\bin\radamsa.exe
seed_pattern:
  "*.pdf"
file_format:
  ".pdf"
