using_autoit:
  yes
path_program:
  C:\Program Files\SumatraPDF\
program_name:
  SumatraPDF.exe
path_autoit_script:
  sample\auto_it_scripts\sumatra.au3 
seed_pattern:
  "*.pdf"
file_format:
  ".pdf"
