arch:
  x86
using_autoit:
  yes
path_program:
  C:\Program Files\Easy RM to MP3 Converter\
program_name:
  RM2MP3Converter.exe 
path_autoit_script:
  sample\auto_it_scripts\easyRmToMp3Converter.au3 
file_format:
  ".m3u"
