run_type:
    winafl_run_targets
input_dir:
    F:\winafl\in_clamav
crash_dir:
    F:\winafl\crash_vlc


targets:
- cov_modules: [libclamav.dll]
  module: libclamav.dll
  offset: '0x8cbe0'
  type: NO_PATH_RECON
- cov_modules: [libclamav.dll, clamscan.exe]
  module: clamscan.exe
  offset: '0x1040'
  type: NO_PATH_RECON
- cov_modules: [libclamav.dll, clamscan.exe]
  module: clamscan.exe
  offset: '0x1000'
  type: NO_PATH_RECON

