/*BEGIN_LEGAL 
Copyright 2004-2016 Intel Corporation. Use of this code is subject to
the terms and conditions of the What If Pre-Release License Agreement,
which is available here:
https://software.intel.com/en-us/articles/what-if-pre-release-license-agreement
or refer to the LICENSE.txt file.
END_LEGAL */
/// @file xed-convert-table-init.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(_XED_CONVERT_TABLE_INIT_H_)
# define _XED_CONVERT_TABLE_INIT_H_
#include "xed-internal-header.h"
typedef struct {

   const char** table_name;

   xed_operand_enum_t opnd;

   unsigned int limit;

} xed_convert_table_t;
extern xed_convert_table_t xed_convert_table[XED_OPERAND_CONVERT_LAST];
#endif
