/*BEGIN_LEGAL 
Copyright 2004-2016 Intel Corporation. Use of this code is subject to
the terms and conditions of the What If Pre-Release License Agreement,
which is available here:
https://software.intel.com/en-us/articles/what-if-pre-release-license-agreement
or refer to the LICENSE.txt file.
END_LEGAL */
/// @file xed-init-pointer-names.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(_XED_INIT_POINTER_NAMES_H_)
# define _XED_INIT_POINTER_NAMES_H_
#include "xed-internal-header.h"
#define XED_MAX_POINTER_NAMES 65
#endif
