---
- hosts: localhost
  connection: local
  vars_files: 
    - config.yaml
  tasks:
    - vsphere_guest:
            vcenter_hostname: '{{ ipvcenter }}'
            username: '{{ username }}'
            password: '{{ rootpassword }}'
            guest: '{{ template }}_{{ run_uid }}_{{ item }}'
            from_template: yes
            power_on_after_clone: yes
            template_src: '{{ template }}'
            validate_certs: no
            esxi:
                datacenter: Datacenter
                hostname: '{{ ipesxi }}'
      with_sequence: start=0 count='{{ number_worker }}'

