# Mandatory Information
path_autoit:
 C:\Program Files\AutoIt3
path_windbg:
 C:\Program Files\Windows Kits\10\Debuggers
path_radamsa:
 C:\cygwin\bin
path_dynamorio:
 C:\Users\monty\DynamoRIO
path_winafl:
 C:\Users\monty\winafl
path_vmfuzz:
 E:\vmfuzz

# Autoit Information
path_autoit_working_dir:
 C:\Users\monty\Desktop\autoit 

# Fuzzers Information
fuzzers:
 - radamsa
 - winafl

# Radamsa Information
path_radamsa_working_dir:
 F:\radamsa

# Winafl Information
path_winafl_working_dir:
 F:\winafl3

