# command that builds the fuzzable
build:
  - mkdir -p build
  - cd build
  - cmake ..
  - make fuzz_target_parse

# path to the fuzzable
executable:
  build/.fuzzci/target_parse/fuzz_target_parse

# corpus that should be used
# also used as the artifact_prefix unless overridden in options
corpus:
  .fuzzci/target_parse/corpus/

# additional options taken by libFuzzer
options:
  '-close_fd_mask': 3