/*BEGIN_LEGAL 
Copyright 2004-2016 Intel Corporation. Use of this code is subject to
the terms and conditions of the What If Pre-Release License Agreement,
which is available here:
https://software.intel.com/en-us/articles/what-if-pre-release-license-agreement
or refer to the LICENSE.txt file.
END_LEGAL */
/// @file xed-operand-ctype-map.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(_XED_OPERAND_CTYPE_MAP_H_)
# define _XED_OPERAND_CTYPE_MAP_H_
#include "xed-internal-header.h"
xed_operand_ctype_enum_t xed_operand_get_ctype(xed_operand_enum_t opname);
unsigned int xed_operand_decider_get_width(xed_operand_enum_t opname);
#endif
