/*BEGIN_LEGAL 
Copyright 2004-2016 Intel Corporation. Use of this code is subject to
the terms and conditions of the What If Pre-Release License Agreement,
which is available here:
https://software.intel.com/en-us/articles/what-if-pre-release-license-agreement
or refer to the LICENSE.txt file.
END_LEGAL */
/// @file xed-gen-table-defs.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(_XED_GEN_TABLE_DEFS_H_)
# define _XED_GEN_TABLE_DEFS_H_
#define XED_ICLASS_NAME_STR_MAX 110
#define XED_MAX_ATTRIBUTE_COUNT 86
#define XED_MAX_INST_TABLE_NODES 6403
#define XED_MAX_OPERAND_TABLE_NODES 1316
#define XED_MAX_OPERAND_SEQUENCES 7714
#define XED_MAX_REQUIRED_SIMPLE_FLAGS_ENTRIES 94
#define XED_MAX_REQUIRED_COMPLEX_FLAGS_ENTRIES 37
#define XED_MAX_GLOBAL_FLAG_ACTIONS 410
#define XED_MAX_IFORMS_PER_ICLASS 28
#define XED_MAX_REQUIRED_ATTRIBUTES 183
#define XED_MAX_CONVERT_PATTERNS 5
#define XED_MAX_DECORATIONS_PER_OPERAND 3
#endif
