/*BEGIN_LEGAL 
Copyright 2004-2016 Intel Corporation. Use of this code is subject to
the terms and conditions of the What If Pre-Release License Agreement,
which is available here:
https://software.intel.com/en-us/articles/what-if-pre-release-license-agreement
or refer to the LICENSE.txt file.
END_LEGAL */
/// @file xed-encoder-gen-defs.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(_XED_ENCODER_GEN_DEFS_H_)
# define _XED_ENCODER_GEN_DEFS_H_
#define XED_ENCODE_ORDER_MAX_ENTRIES  32
#define XED_ENCODE_ORDER_MAX_OPERANDS 5
#define XED_ENCODE_MAX_FB_PATTERNS 105
#define XED_ENCODE_MAX_EMIT_PATTERNS 168
#define XED_ENCODE_FB_VALUES_TABLE_SIZE 5421
#define XED_ENCODE_MAX_IFORMS 6423
#define XED_ENC_GROUPS 462
#endif
