using_autoit:
  no
path_program: 
  C:\Program Files\VideoLAN\VLC\
program_name:
  vlc.exe
auto_close:
  false
running_time:
  5
path_radamsa:
  C:\cygwin\bin\radamsa.exe
seed_pattern:
  "*.mp3"
file_format:
  ".mp3"
