path_program: 
  C:\Program Files\SumatraPDF\
program_name:
  SumatraPDF.exe
using_autoit:
  yes
path_autoit_script:
  C:\Users\monty\Desktop\my_tests\sumatra.au3 
seed_pattern:
  "*.pdf"
file_format:
  ".pdf"
